name: telegram-vlc-stream-bot

services:
  - name: telegram-stream-bot
    type: web
    docker:
      dockerfile: Dockerfile
    ports:
      - port: 8000
        protocol: http
    env:
      - name: API_ID
      - name: API_HASH
      - name: BOT_TOKEN
      - name: URL
      - name: DATABASE_URL
      - name: ADMINS
      - name: LOG_CHANNEL
    health_checks:
      - http:
          port: 8000
          path: /
    instance_type: free
    regions:
      - fra